### ISSUE TITLE
About circuits construction

### ISSUE THREAD

**Issue by prvsousa** [AarhusCrypto/DUPLO#6]
One question, for comparison of 4 characters I made this circuit:

```
6 19
4 4 2

2 1 0 4 8 XOR
2 1 1 5 9 XOR
2 1 2 6 10 XOR
2 1 3 7 11 XOR
1 1 8 12 INV
1 1 9 13 INV
1 1 10 14 INV
1 1 11 15 INV
2 1 12 13 16 AND
2 1 14 15 17 AND
2 1 16 17 18 AND
```

This is based on the circuit that we construct https://github.com/AarhusCrypto/TinyLEGO/issues/1#issuecomment-306054939 here.

My though was something like this:
```

0 0 0 1 - input1
0 1 0 1 - input2
0 1 0 0 - XOR
1 0 1 1 - INV
\ /   \ /
  0    1  - AND
   \   /
     0    - AND 
```

But the output in the program gives the response "1". Can you help me with this? My circuit is wrong?

**Comment by RobTrifiletti** [comment]
You are here comparing 4 bits, not 4 characters. So this circuit should output 1 iff input1[0;3] == input2[0;3]

It seems to be correct to me (I also ran it), apart that the second line should be change to
4 4 1
as there is only a single output-bit, 0 if input1 != input 2, 1 if they are equal.

**Comment by prvsousa** [comment]
Oh, ok. So, for 4 characters input1[0,0,0,1] I assume that is 0 1 2 3 and 4 5 6 7 for input2, but I'm thinking wrong so?

I need more 4 wires?

**Comment by RobTrifiletti** [comment]
It depends on what you have defined a character to be. In this case it looks like to me that you are comparing two single characters, encoded using 4-bits each. That is how I would interpret this circuit at least. You can also say that you are comparing 2 binary vectors in v_1, v2 \in {0,1}^4, same thing really, but perhaps easier to see it that way.

**Comment by prvsousa** [comment]
Basically, i'm comparing
input[0]=0
input[1]=0
input[2]=0
input[3]=1

With the circuit above, I get "0" with input1=0001 and input2=0001 too, for example. And I don't know if I'm doing something wrong for this example

**Comment by RobTrifiletti** [comment]
What do you mean by comparing
"input[0]=0
input[1]=0
input[2]=0
input[3]=1"?

When I run the following code it outputs 1
`
Circuit circuit = read_bristol_circuit("test.txt");
  osuCrypto::BitVector input(circuit.num_inp_wires);
  input[3] = 1;
  input[7] = 1;
  osuCrypto::BitVector res = eval_circuit(circuit, input);
  PrintBin(res.data(), circuit.num_out_wires);
`

If you want to compare the bits it is much easier. You just compute the XOR of the inputs. This is secure since in the binary case if I know your bit is not equal mine to mine, then I also know your bit.

**Comment by prvsousa** [comment]
I'm confusing something... Why you put input[3] and input[7] , 3 and 7?

Basically, I want that P1 gives 0001 and P2 gives also 0001 and so, compare both and see if are equal.

I.e.,

`Circuit circuit = read_bristol_circuit("test.txt"); osuCrypto::BitVector input(circuit.num_inp_wires); input[0] = 0; input[1] = 0; input[2]= 0; input[3]=1; osuCrypto::BitVector res = eval_circuit(circuit, input); PrintBin(res.data(), circuit.num_out_wires);`

**Comment by RobTrifiletti** [comment]
In this case I just run the circuit eval code. Think of that as an interpreter that takes a circuit and an input and returns the output. It doesn't do any secure computation, network communication, etc. Its just a local quick way of verifying the circuit evaluates as you expect.

So in this case all 8 inputs are passed to the circuit as a single array. Hope that cleared it up :)

**Comment by prvsousa** [comment]
I'm confused, a lot.

Do you remember this: https://github.com/AarhusCrypto/TinyLEGO/issues/1#issuecomment-305784533?

Basically instead of the 8 bits that I compare there, I want only 4... 0 0 0 1

So, I follow the same path with a circuit. I'm not understand what is the problem .

**Comment by RobTrifiletti** [comment]
Sorry to confuse you :)

I remember that circuit yes, but here's the thing. You were not comparing 8-bits, you were comparing an 8-bit vector to another 8-bit vector. The output is 1 iff the vectors are equal in all 8 positions, else it's 0. Here you have correctly transferred the circuit to the 4-bit vector case.

I am however also confused if this is what you want, or if you just want to compare the bits one by one, i.e comparing 4 1-bit vectors? If that is the case then this circuit does not do that.

**Comment by prvsousa** [comment]
No problem and thanks!
Ok, let's start by the first case. I can compare all the 4 positions of the vector, i.e. 4 bit vector.

But with my current state, a vector with [0,0,0,1] comparing with another vector with [0,0,0,1] gives me output 0, and I thought that it was an error in the circuit

**Comment by RobTrifiletti** [comment]
I just ran your circuit on that input and it outputs 1 as it should. Can you show me the code you are running?

**Comment by prvsousa** [comment]
I change in the duplo-const-main.cpp
```

  osuCrypto::BitVector inputs(composed_circuit.num_const_inp_wires); //0 input
  if (!circuit_name.empty()) {
    inputs[0] = 0;
    inputs[1] = 0;
    inputs[2] = 0;
    inputs[3] = 1;
  
  }
```

And in the duplo-eval-main.cpp, same way

```
osuCrypto::BitVector inputs(composed_circuit.num_eval_inp_wires); // 0 input
  BYTEArrayVector output_keys(composed_circuit.num_out_wires, CSEC_BYTES);
  
  
  if (!circuit_name.empty()) {
    inputs[0] = 0;
    inputs[1] = 0;
    inputs[2] = 0;
    inputs[3] = 1;
  }

```

**Comment by RobTrifiletti** [comment]
Hmm, that looks fine. When I run that the circuit outputs 1 correctly also. How do you check the output?

**Comment by prvsousa** [comment]
`std::cout << outputs[0][0] << std::endl;   `

This way. And I get:
```
====== 1 x const_1 ======
====== test/data/comparison.txt ======
====== 1 x eval_1 ======
====== test/data/comparison.txt ======
0
Setup ms: 130.368, data sent: 12.698 kB
Circuit Preprocess ms: 2.08954, data sent: 75.534 kB
Setup ms: 129.902, data sent: 16.547 kB
Auth Preprocess ms: 3.01199, data sent: 161.514 kB
Circuit Preprocess ms: 2.15556, data sent: 0.081 kB
Auth Preprocess ms: 3.07474, data sent: 0.161 kB
Build ms: 3.34737, data sent: 22.394 kB
Eval circuits ms: 1.07778, data sent: 0.002 kB
Decode keys ms: 0.135507, data sent: 0.017 kB
=============================
Preprocess ms: 5.2303, data sent: 0.242 kB
Build ms: 3.34737, data sent: 22.394 kB
Online ms: 1.21328, data sent: 0.019 kB
( 1, 5.2303, 3.34737, 1.21328)
( 1, 9.79096)
=============================
Build ms: 3.30544, data sent: 32.747 kB
Eval circuits ms: 0.142819, data sent: 0.593 kB
Decode keys ms: 0.081011, data sent: 0.067 kB
=============================
Preprocess ms: 5.10153, data sent: 237.048 kB
Build ms: 3.30544, data sent: 32.747 kB
Online ms: 0.22383, data sent: 0.66 kB
( 1, 237.048, 32.747, 0.66)
( 1, 270.455)
=============================

```

**Comment by RobTrifiletti** [comment]
Hmm, that looks correct too. What is the terminal command you run? We must be doing something different somewhere.
You did change the second line to 4 4 1?

**Comment by prvsousa** [comment]
Yes, I did.

Can you show me how do you run the program? It's strange that we all have the same and do not work here.

**Comment by prvsousa** [comment]
I don't know if it helps, but I tried also with TinyLEGO and I have more or less the same problem. Let's say, with input 
```
const_input[0]=0    eval_input[0]=0
const_input[1]=0    eval_input[1]=0
const_input[2]=0    eval_input[2]=0
const_input[3]=1    eval_input[3]=1
```
I get "1" but with: 
```
all outputs not equal for 2
all outputs not equal for 2
all outputs not equal for 2
all outputs not equal for 2
all outputs not equal for 2
all outputs not equal for 2
...
```
this output multiple times...

With the input "0011" in both sides, the same occurs but with "0". I don't know, but maybe the circuit is the problem, because with other circuits the libraries worked always well!

**Comment by RobTrifiletti** [comment]
I run the following in two different terminal windows
./build/release/DuploConstructor -ip localhost -n 1 -f test.txt -b 1
./build/release/DuploEvaluator -ip localhost -n 1 -f test.txt -b 1

where test.txt contains:
———————
6 19
4 4 1

2 1 0 4 8 XOR
2 1 1 5 9 XOR
2 1 2 6 10 XOR
2 1 3 7 11 XOR
1 1 8 12 INV
1 1 9 13 INV
1 1 10 14 INV
1 1 11 15 INV
2 1 12 13 16 AND
2 1 14 15 17 AND
2 1 16 17 18 AND

———————

**Comment by prvsousa** [comment]
Oh, I have to say sorry!! The  4 4 1 solves the problem... I delete the last line of the circuit in this two last tests because of test reasons and I forget to fix the circuit again. So sorry ! And thanks for help!
